In [ ]:
import pandas as pd
import numpy as np
import random

In [ ]:
# Create a dictionary with random data for the 5 features
data = {
    'OrderID': [random.randint(1000, 1999) for _ in range(10)],
    'ShipMode': [random.choice(['FirstClass', 'SecondClass','StandardClass']) for _ in range(10)],
    'Segment': [random.choice(['Consumer', 'Corporate', 'HomeOffice']) for _ in range(10)],
    'Quantity': [random.randint(10, 200) for _ in range(10)],
    'Profit': [random.randint(500, 2000) for _ in range(10)]
}

# Create the DataFrame
df = pd.DataFrame(data)

In [ ]:
df

   OrderID       ShipMode     Segment  Quantity  Profit
0     1091     FirstClass   Corporate        93     643
1     1171  StandardClass    Consumer        45     961
2     1463    SecondClass   Corporate       171     562
3     1919    SecondClass  HomeOffice       187     745
4     1052     FirstClass  HomeOffice       199    1423
5     1838    SecondClass    Consumer       110    1192
6     1213    SecondClass   Corporate        16     853
7     1366     FirstClass    Consumer        70    1087
8     1019     FirstClass  HomeOffice        94    1733
9     1095     FirstClass   Corporate        76    1120

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   10 non-null     int64
 1   ShipMode  10 non-null     object
 2   Segment   10 non-null     object
 3   Quantity  10 non-null     int64
 4   Profit    10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 528.0+ bytes

In [ ]:
df.describe()

           OrderID   Quantity      Profit
count    10.000000   10.00000    10.00000
mean   1322.700000  106.10000  1031.90000
std     324.680715   61.26527   360.91287
min    1019.000000   16.00000   562.00000
25%    1092.000000   71.50000   772.00000
50%    1192.000000   93.50000  1024.00000
75%    1438.750000  155.75000  1174.00000
max    1919.000000  199.00000  1733.00000

In [ ]:
df.loc[4]

OrderID           1052
ShipMode    FirstClass
Segment     HomeOffice
Quantity           199
Profit            1423
Name: 4, dtype: object

In [ ]:
df.isnull().sum()

OrderID     0
ShipMode    0
Segment     0
Quantity    0
Profit      0
dtype: int64

In [ ]:
df.isnull()

   OrderID  ShipMode  Segment  Quantity  Profit
0    False     False    False     False   False
1    False     False    False     False   False
2    False     False    False     False   False
3    False     False    False     False   False
4    False     False    False     False   False
5    False     False    False     False   False
6    False     False    False     False   False
7    False     False    False     False   False
8    False     False    False     False   False
9    False     False    False     False   False